marks= []
f1=input("Enter marks :")
marks.append(f1)
f2=input("Enter marks :")
marks.append(f2)
f3=input("Enter marks :")
marks.append(f3)
f4=input("Enter marks :")
marks.append(f4)
f5=input("Enter marks :")
marks.append(f5)
f6=input("Enter marks :")
marks.append(f6)
f7=input("Enter marks :")
marks.append(f7)
marks.sort()
print(marks)
# print(sorting)2
